package com.example.facilityprojects.model

class Server {
    companion object {
        /*var host: String = "facilityshop1236.000webhostapp.com/facilityshop" // Your website address*/
        var host: String = "192.168.1.9" // Your ip address
        var userInfo = "http://" + host + "/user/userInfo.php"
        var login = "http://" + host + "/user/login.php"
        var fbUserInfo = "http://" + host + "/user/fbUserInfo.php"
        var googleUserInfo = "http://" + host + "/user/googleUserInfo.php"
        var getCategory = "http://" + host + "/user/getCategory.php"
        var getProductByType = "http://" + host + "/user/getProductByType.php"
        var getProductByCategory = "http://" + host + "/user/getProductByCategory.php"
        var getSeemoreProduct = "http://" + host + "/user/getSeemoreProduct.php"
        var detailProduct = "http://" + host + "/user/detailProduct.php"
        var saveCart = "http://" + host + "/user/saveCart.php"
        var getCart = "http://" + host + "/user/getCart.php"
        var removeCart = "http://" + host + "/user/removeCart.php"
        var removeAllCart = "http://" + host + "/user/removeAllCart.php"
        var updateCart = "http://" + host + "/user/updateCart.php"
        var getUserInfo = "http://" + host + "/user/getUserInfo.php"
        var getSocialUserInfo = "http://" + host + "/user/getSocialUserInfo.php"
        var updateOnlyPassword = "http://" + host + "/user/updateOnlyPassword.php"
        var updateUserInfo = "http://" + host + "/user/updateUserInfo.php"
        var updateUserInfo2 = "http://" + host + "/user/updateUserInfo2.php"
        var updateUserInfo3 = "http://" + host + "/user/updateUserInfo3.php"
        var updateUserInfo4 = "http://" + host + "/user/updateUserInfo4.php"
        var getUserId = "http://" + host + "/user/getUserId.php"
        var getUserId2 = "http://" + host + "/user/getUserId2.php"
        var updateSecurityQuestion = "http://" + host + "/user/updateSecurityQuestion.php"
        var saveOrder = "http://" + host + "/user/saveOrder.php"
        var saveDetailOrder = "http://" + host + "/user/saveDetailOrder.php"
        var getStateToggleCart = "http://" + host + "/user/getStateToggleCart.php"
        var saveFavourite = "http://" + host + "/user/saveFavourite.php"
        var getFavourite = "http://" + host + "/user/getFavourite.php"
        var removeFavourite = "http://" + host + "/user/removeFavourite.php"
        var getStateToggleFav = "http://" + host + "/user/getStateToggleFav.php"
        var removeAllFav = "http://" + host + "/user/removeAllFav.php"
        var getOrder = "http://" + host + "/user/getOrder.php"
        var removeOrder = "http://" + host + "/user/removeOrder.php"
        var cancelOrder = "http://" + host + "/user/cancelOrder.php"
        var removeAllHistory = "http://" + host + "/user/removeAllHistory.php"
        var getDetailOrder = "http://" + host + "/user/getDetailOrder.php"
        var getSecurityQuestion = "http://" + host + "/user/getSecurityQuestion.php"
        var resetPassword = "http://" + host + "/user/resetPassword.php"
        var getIdOrder = "http://" + host + "/user/getIdOrder.php"
        var getEmailAddress = "http://" + host + "/user/getEmailAddress.php"
        var checkRegister = "http://" + host + "/user/checkRegister.php"
        var filterProduct = "http://" + host + "/user/filterProduct.php"
        var searchProduct = "http://" + host + "/user/searchProduct.php"
        var searchResult = "http://" + host + "/user/searchResult.php"
    }
}